<?xml version="1.0"?>

<!--
License: Apache 2.0. See LICENSE file in root directory.
Copyright(c) 2017 Intel Corporation. All Rights Reserved

This is the URDF model for the Intel RealSense 430 camera, in it's
aluminum peripherial evaluation case.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:macro name="realsense_d435" params="name parent *origin namespace">

        <!-- The following values are approximate, and the camera node
         publishing TF values with actual calibrated camera extrinsic values -->
        <xacro:property name="d435_cam_depth_to_left_ir_offset" value="0.0"/>
        <xacro:property name="d435_cam_depth_to_right_ir_offset" value="-0.050"/>
        <xacro:property name="d435_cam_depth_to_color_offset" value="0.015"/>

        <!-- The following values model the aluminum peripherial case for the
        D435 camera, with the camera joint represented by the actual 
        peripherial camera tripod mount -->
        <xacro:property name="d435_cam_width" value="0.090"/>
        <xacro:property name="d435_cam_height" value="0.025"/>
        <xacro:property name="d435_cam_depth" value="0.02505"/>
        <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>

        <!-- The following offset is relative the the physical D435 camera peripherial
        camera tripod mount -->
        <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
        <xacro:property name="d435_cam_depth_py" value="0.0175"/>
        <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>

        <material name="${name}_aluminum">
            <color rgba="0.5 0.5 0.5 1"/>
        </material>


        <!-- camera body, with origin at bottom screw mount -->
        <joint name="${name}_camera_joint" type="fixed">
            <xacro:insert_block name="origin" />
            <parent link="${parent}"/>
            <child link="${name}_camera_link" />
        </joint>

        <link name="${name}_camera_link">
            <visual>
                <origin xyz="${d435_cam_mount_from_center_offset} 0.0 ${d435_cam_height/2}" rpy="${pi/2} 0 ${pi/2}"/>
                <geometry>
                    <mesh filename="package://kelo_description/meshes/sensors/realsense_d435.dae" />
                </geometry>
                <material name="${name}_aluminum"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 ${d435_cam_height/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${d435_cam_depth} ${d435_cam_width} ${d435_cam_height}"/>
                </geometry>
            </collision>
            <inertial>
                <!-- The following are not reliable values, and should not be used for modeling -->
                <mass value="0.564" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
            </inertial>
        </link>

        <!-- camera depth joints and links -->
        <joint name="${name}_camera_depth_joint" type="fixed">
            <origin xyz="${d435_cam_depth_px} ${d435_cam_depth_py} ${d435_cam_depth_pz}" rpy="0 0 0"/>
            <parent link="${name}_camera_link"/>
            <child link="${name}_camera_depth_frame" />
        </joint>
        <link name="${name}_camera_depth_frame"/>

        <joint name="${name}_camera_depth_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
            <parent link="${name}_camera_depth_frame" />
            <child link="${name}_camera_depth_optical_frame" />
        </joint>
        <link name="${name}_camera_depth_optical_frame"/>

        <!-- camera left IR joints and links -->
        <joint name="${name}_camera_left_ir_joint" type="fixed">
            <origin xyz="0 ${d435_cam_depth_to_left_ir_offset} 0" rpy="0 0 0" />
            <parent link="${name}_camera_depth_frame" />
            <child link="${name}_camera_left_ir_frame" />
        </joint>
        <link name="${name}_camera_left_ir_frame"/>

        <joint name="${name}_camera_left_ir_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
            <parent link="${name}_camera_left_ir_frame" />
            <child link="${name}_camera_left_ir_optical_frame" />
        </joint>
        <link name="${name}_camera_left_ir_optical_frame"/>

        <!-- camera right IR joints and links -->
        <joint name="${name}_camera_right_ir_joint" type="fixed">
            <origin xyz="0 ${d435_cam_depth_to_right_ir_offset} 0" rpy="0 0 0" />
            <parent link="${name}_camera_depth_frame" />
            <child link="${name}_camera_right_ir_frame" />
        </joint>
        <link name="${name}_camera_right_ir_frame"/>

        <joint name="${name}_camera_right_ir_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
            <parent link="${name}_camera_right_ir_frame" />
            <child link="${name}_camera_right_ir_optical_frame" />
        </joint>
        <link name="${name}_camera_right_ir_optical_frame"/>

        <!-- camera color joints and links -->
        <joint name="${name}_camera_color_joint" type="fixed">
            <origin xyz="0 ${d435_cam_depth_to_color_offset} 0" rpy="0 0 0" />
            <parent link="${name}_camera_depth_frame" />
            <child link="${name}_camera_color_frame" />
        </joint>
        <link name="${name}_camera_color_frame"/>

        <joint name="${name}_camera_color_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
            <parent link="${name}_camera_color_frame" />
            <child link="${name}_camera_color_optical_frame" />
        </joint>
        <link name="${name}_camera_color_optical_frame"/>

        <gazebo reference="${name}_camera_link">
            <sensor type="depth" name="${name}_depth_sensor">
                <update_rate>20.0</update_rate>
                <camera name="${name}_camera">
                    <horizontal_fov>1.21</horizontal_fov>
                    <image>
                        <width>640</width>
                        <height>360</height>
                        <format>B8G8R8</format>
                    </image>
                    <clip>
                        <near>0.13</near>
                        <far>30.0</far>
                    </clip>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.007</stddev>
                    </noise>
                </camera>
                <plugin name="${name}_realsense_d435_plugin" filename="libgazebo_ros_openni_kinect.so">
                    <baseline>0.2</baseline>
                    <alwaysOn>true</alwaysOn>
                    <updateRate>0.0</updateRate>
                    <cameraName>${name}_camera</cameraName>
                    <imageTopicName>/${namespace}/${name}_camera/color/image_raw</imageTopicName>
                    <cameraInfoTopicName>/${namespace}/${name}_camera/color/camera_info</cameraInfoTopicName>
                    <depthImageTopicName>/${namespace}/${name}_camera/depth/image_raw</depthImageTopicName>
                    <depthImageInfoTopicName>/${namespace}/${name}_camera/depth/camera_info</depthImageInfoTopicName>
                    <pointCloudTopicName>/${namespace}/${name}_camera/depth_registered/points</pointCloudTopicName>
                    <frameName>/${namespace}/${name}_camera_depth_optical_frame</frameName>
                    <pointCloudCutoff>0.105</pointCloudCutoff>
                    <pointCloudCutoffMax>10.0</pointCloudCutoffMax>
                    <distortionK1>0.00000001</distortionK1>
                    <distortionK2>0.00000001</distortionK2>
                    <distortionK3>0.00000001</distortionK3>
                    <distortionT1>0.00000001</distortionT1>
                    <distortionT2>0.00000001</distortionT2>
                    <CxPrime>0</CxPrime>
                    <Cx>0</Cx>
                    <Cy>0</Cy>
                    <focalLength>0</focalLength>
                    <hackBaseline>0</hackBaseline>
                </plugin>
            </sensor>
        </gazebo>

    </xacro:macro>

</robot>
